general:
  loggerName: performer
  conductorEndpoint: tcp://10.0.0.181:44441
  fasciaEndpoint: tcp://0.0.0.0:44449

ledMatrix:
  width: 74
  height: 10

ws2812b:
  gpioNumber: 18
  pwmChannel: 0
  initialBrightness: 5
  # if flickering occurs, try throttling refresh rate to ledCount * 30
  refreshRate: 2500
